namespace: nsse
nameSuffix: -prod
namePrefix: nsse-
labels:
- includeTemplates: true
  pairs:
    application: not-so-simple-ecommerce
resources:
- infraestructure/namespace.yml
- infraestructure/config-map.yml
- infraestructure/service-account.yml
- infraestructure/secrets/ecr-image-pull-credentials.yml
- infraestructure/secrets/kestrel-certificate.yml
- infraestructure/secrets/mongo-certificate.yml
- infraestructure/ingress.yml
- infraestructure/network-policies/ingress.yml
- infraestructure/network-policies/egress.yml
- infraestructure/analysis-template.yml

helmGlobals:
  chartHome: application

  # - name: health-checker
  #   version: 0.1.0
  #   releaseName: health-checker
  #   namespace: nsse
  #   valuesFile: application/health-checker/values.yaml


  # - name: invoice-generator
  #   version: 0.1.0
  #   releaseName: invoice-generator
  #   namespace: nsse
  #   valuesFile: application/invoice-generator/values.yaml


  # - name: notificator
  #   version: 0.1.0
  #   releaseName: notificator
  #   namespace: nsse
  #   valuesFile: application/notificator/values.yaml

helmCharts:
- name: identity-server
  namespace: nsse
  releaseName: identity-server
  valuesFile: application/identity-server/values.yaml
  version: 0.1.0
- name: main
  namespace: nsse
  releaseName: main
  valuesFile: application/main/values.yaml
  version: 0.1.0
- name: order
  namespace: nsse
  releaseName: order
  valuesFile: application/order/values.yaml
  version: 0.1.0



  
  


images:
- name: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/health-checker
  newName: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/health-checker
  newTag: latest
- name: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/identity-server
  newName: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/identity-server
  newTag: latest
- name: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/invoice-generator
  newName: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/invoice-generator
  newTag: latest
- name: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/main
  newName: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/main
  newTag: e71e50a
- name: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/notificator
  newName: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/notificator
  newTag: latest
- name: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/order
  newName: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/order
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
