apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.identityServerDeployment.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.identityServerDeployment.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.identityServerDeployment.autoscaling.averageCpuUtilization }}
  behavior:
    scaleDown:
      {{- toYaml .Values.identityServerDeployment.autoscaling.scaleDown | nindent 6}}
    scaleUp:
      {{- toYaml .Values.identityServerDeployment.autoscaling.scaleUp | nindent 6}}