apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "https://+:4443"
  ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH: "/nsse-backend/certificates/kestrel/certificate.pfx"
  ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PASSWORD: "DevOpsNaNuvem0!"

  BASEADDRESS__MAIN: "https://s2sinovatec.com/main"
  BASEADDRESS__IDENTITY: "https://s2sinovatec.com/identity"
  BASEADDRESS__ORDER: "https://s2sinovatec.com/order"

  LOCALSTACK__ISENABLED: "false"

  MONGO__DATABASE: "notSoSimpleEcommerce"
  MONGO__REPORT_COLLECTION: "reports"
  MONGO_CERTIFICATE_CONTAINER_PATH: "/nsse-backend/certificates/mongo/certificate.pem"

  CONNECTIONSTRINGS__DEFAULT: 'User ID=nsseAdmin;Password=C$k5Rw0q#[_3Ovl6dEy[d6-J9OnB;Host=nsse-aurora-serverless-cluster-proxy.proxy-c41asik4843g.us-east-1.rds.amazonaws.com;Port=5432;Database=notSoSimpleEcommerce;Include Error Detail=true'
  CONNECTIONSTRINGS__MONGO: "mongodb://nsse:DU%28%3FDR%28KI1K%2ADSJP_detM%5Dp4qLA~@nsse-documentdb-cluster-instance.c41asik4843g.us-east-1.docdb.amazonaws.com:27017/admin?ssl=true&sslInvalidHostNameAllowed=true&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-1"

  AWSS3PARAMS01__BUCKETNAME: "nsse-application-bucket-p"
  AWSS3PARAMS01__URIEXPIRATIONMINUTES: "60"

  IDENTITY__ISSUER: "https://s2sinovatec.com/identity"
  IDENTITY__AUDIENCE: "https://s2sinovatec.com"
  IDENTITY__TOKENLIFETIME: "60"
  IDENTITY__ADMIN__USER: "admin@nsse.com"
  IDENTITY__ADMIN__USER__PASSWORD: "<YOUR-ENCRYPTED-PASSWORD>"
  IDENTITY__KEY: "<YOUR-ENCRYPTED-KEY>"

  HEALTHCHECKSUI__HEALTHCHECKS__0__NAME: "Postgresql"
  HEALTHCHECKSUI__HEALTHCHECKS__0__URI: "https://s2sinovatec.com/healthchecks/health"

  HEALTHCHECKSUI__HEALTHCHECKS__1__NAME: "Main"
  HEALTHCHECKSUI__HEALTHCHECKS__1__URI: "https://s2sinovatec.com/main/health"

  HEALTHCHECKSUI__HEALTHCHECKS__2__NAME: "Order"
  HEALTHCHECKSUI__HEALTHCHECKS__2__URI: "https://s2sinovatec.com/order/health"

  HEALTHCHECKSUI__HEALTHCHECKS__3__NAME: "Notificator"
  HEALTHCHECKSUI__HEALTHCHECKS__3__URI: "https://s2sinovatec.com/notificator/health"

  HEALTHCHECKSUI__HEALTHCHECKS__4__NAME: "Identity Server"
  HEALTHCHECKSUI__HEALTHCHECKS__4__URI: "https://s2sinovatec.com/identity/health"

  HEALTHCHECKSUI__HEALTHCHECKS__5__NAME: "Invoice Generator"
  HEALTHCHECKSUI__HEALTHCHECKS__5__URI: "https://s2sinovatec.com/invoice/health"

  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__QUEUENAME: "EmailNotificationQueue"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__QUEUEOWNERAWSACCOUNTID: "495624154773"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__MAXNUMBEROFMESSAGES: "10"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__WAITTIMESECONDS: "10"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__MSGPROCESSORSERVICENAME: "AwsSesEmailSenderProcessor"
  NOTIFICATOR__AWSSQSQUEUEMONITORPARAMS01__MILLISECONDSDELAY: "1000"
  NOTIFICATOR__EMAILCONFIGURATION__FROM: "support@s2sinovatec.com"
  NOTIFICATOR__EMAILCONFIGURATION__TO: "pauloedhuardo@gmail.com"
  NOTIFICATOR__EMAILCONFIGURATION__SESTEMPLATE: "order-confirmed-template"

  MAIN__AWSSQSQUEUEMONITORPARAMS01__QUEUENAME: "ProductStockQueue"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__QUEUEOWNERAWSACCOUNTID: "495624154773"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__MAXNUMBEROFMESSAGES: "10"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__WAITTIMESECONDS: "10"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__MSGPROCESSORSERVICENAME: "ProductStockProcessor"
  MAIN__AWSSQSQUEUEMONITORPARAMS01__MILLISECONDSDELAY: "1000"

  ORDER__AWSSQSMESSAGESENDERPARAMS01__QUEUENAME: "EmailNotificationQueue"
  ORDER__AWSSQSMESSAGESENDERPARAMS01__QUEUEOWNERAWSACCOUNTID: "495624154773"
  ORDER__AWSSQSMESSAGESENDERPARAMS01__ISFIFO: "false"
  ORDER__AWSSQSMESSAGESENDERPARAMS01__ENABLEMESSAGEDEDUPLICATION: "false"

  ORDER__AWSSQSMESSAGESENDERPARAMS02__QUEUENAME: "ProductStockQueue"
  ORDER__AWSSQSMESSAGESENDERPARAMS02__QUEUEOWNERAWSACCOUNTID: "495624154773"
  ORDER__AWSSQSMESSAGESENDERPARAMS02__ISFIFO: "false"
  ORDER__AWSSQSMESSAGESENDERPARAMS02__ENABLEMESSAGEDEDUPLICATION: "false"

  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__QUEUENAME: "InvoiceQueue"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__QUEUEOWNERAWSACCOUNTID: "495624154773"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__MAXNUMBEROFMESSAGES: "10"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__WAITTIMESECONDS: "10"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__MSGPROCESSORSERVICENAME: "InvoiceProcessor"
  INVOICEGENERATOR__AWSSQSQUEUEMONITORPARAMS01__MILLISECONDSDELAY: "1000"

  INVOICEGENERATOR__AWSSQSMESSAGESENDERPARAMS01__QUEUENAME: "EmailNotificationQueue"
  INVOICEGENERATOR__AWSSQSMESSAGESENDERPARAMS01__QUEUEOWNERAWSACCOUNTID: "495624154773"
  INVOICEGENERATOR__AWSSQSMESSAGESENDERPARAMS01__ISFIFO: "false"
  INVOICEGENERATOR__AWSSQSMESSAGESENDERPARAMS01__ENABLEMESSAGEDEDUPLICATION: "false"