apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.invoiceGeneratorDeployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      topologySpreadConstraints:
      {{- range .Values.invoiceGeneratorDeployment.topologySpreadConstraints }}
      - maxSkew:  {{ .maxSkew }}
        topologyKey: {{ .topologyKey }}
        whenUnsatisfiable: {{ .whenUnsatisfiable }}
        labelSelector:
          matchLabels:
            app: {{ $.Release.Name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.invoiceGeneratorDeployment.securityContext | nindent 8}}
      serviceAccount: {{ .Values.invoiceGeneratorDeployment.serviceAccount }}
      volumes:
        {{- toYaml .Values.invoiceGeneratorDeployment.volumes | nindent 6 }}
      imagePullSecrets:
      - name: {{ .Values.invoiceGeneratorDeployment.imagePullSecrets }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.invoiceGeneratorDeployment.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.invoiceGeneratorDeployment.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.invoiceGeneratorDeployment.configMap }}
        volumeMounts:
          {{- toYaml .Values.invoiceGeneratorDeployment.volumeMounts | nindent 8}}
        resources:
          {{- toYaml .Values.invoiceGeneratorDeployment.resources | nindent 10}}
        livenessProbe:
          {{- toYaml .Values.invoiceGeneratorDeployment.livenessProbe | nindent 10}}
        readinessProbe:
          {{- toYaml .Values.invoiceGeneratorDeployment.readinessProbe | nindent 10}}
