apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Values.mainDeployment.rolloutName }}
  minReplicas: {{ .Values.mainDeployment.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.mainDeployment.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.mainDeployment.autoscaling.averageCpuUtilization }}
  behavior:
    scaleDown:
      {{- toYaml .Values.mainDeployment.autoscaling.scaleDown | nindent 6}}
    scaleUp:
      {{- toYaml .Values.mainDeployment.autoscaling.scaleUp | nindent 6}}