apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.mainDeployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    blueGreen:
      activeService: {{ .Values.mainDeployment.activeService }}
      previewService: {{ .Values.mainDeployment.previewService }}
      autoPromotionEnabled: {{ .Values.mainDeployment.blueGreen.autoPromotionEnabled }}
      scaleDownDelaySeconds: {{ .Values.mainDeployment.blueGreen.scaleDownDelaySeconds }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      topologySpreadConstraints:
      {{- range .Values.mainDeployment.topologySpreadConstraints }}
      - maxSkew:  {{ .maxSkew }}
        topologyKey: {{ .topologyKey }}
        whenUnsatisfiable: {{ .whenUnsatisfiable }}
        labelSelector:
          matchLabels:
            app: {{ $.Release.Name }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.mainDeployment.securityContext | nindent 8}}
      serviceAccount: {{ .Values.mainDeployment.serviceAccount }}
      volumes:
        {{- toYaml .Values.mainDeployment.volumes | nindent 6 }}
      imagePullSecrets:
      - name: {{ .Values.mainDeployment.imagePullSecrets }}
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.mainDeployment.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.mainDeployment.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Values.mainDeployment.configMap }}
        volumeMounts:
          {{- toYaml .Values.mainDeployment.volumeMounts | nindent 8}}
        resources:
          {{- toYaml .Values.mainDeployment.resources | nindent 10}}
        livenessProbe:
          {{- toYaml .Values.mainDeployment.livenessProbe | nindent 10}}
        readinessProbe:
          {{- toYaml .Values.mainDeployment.readinessProbe | nindent 10}}
