mainDeployment:
  image: 495624154773.dkr.ecr.us-east-1.amazonaws.com/nsse/production/main
  imagePullSecrets: nsse-ecr-image-pull-credentials-prod
  autoscaling:
    minReplicas: 1
    maxReplicas: 3
    averageCpuUtilization: 50
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        value: 2
        periodSeconds: 15
      - type: Percent
        value: 50
        periodSeconds: 15
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 15
      selectPolicy: Max
  containerPort: 4443
  nodePort: 30002
  configMap: nsse-config-map-prod
  replicaCount: 1
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
  securityContext:
        runAsUser: 1000
        runAsGroup: 1000
  serviceAccount: nsse-sa-prod
  volumes:
  - name: kestrel
    secret:
      secretName: nsse-kestrel-certificate-prod
  - name: mongo
    secret:
      secretName: nsse-mongo-certificate-prod
  volumeMounts:
  - name: kestrel
    mountPath: /nsse-backend/certificates/kestrel
    readOnly: true
  - name: mongo
    mountPath: /nsse-backend/certificates/mongo
    readOnly: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  livenessProbe:
    httpGet:
      path: /main/health
      port: 4443
      scheme: HTTPS
    successThreshold: 1
    failureThreshold: 3
    initialDelaySeconds: 120
    timeoutSeconds: 15
    periodSeconds: 60
  readinessProbe:
    httpGet:
      path: /main/health
      port: 4443
      scheme: HTTPS
    successThreshold: 1
    failureThreshold: 3
    initialDelaySeconds: 3
    timeoutSeconds: 15
    periodSeconds: 3